- hosts: demo
  gather_facts: no
  tasks:
    - name: Test privileged account
      ansible.windows.win_ping:

#    - name: Print variables
#      debug:
#        msg: "Username: {{ account.username }}, Password: {{ account.secret }}"


    - name: Get groups of a Windows user
      ansible.windows.win_user:
        name: "{{ jms_account.username }}"
      register: user_info

    - name: Change password
      ansible.windows.win_user:
        name: "{{ account.username }}"
        password: "{{ account.secret }}"
        groups: "{{ user_info.groups[0].name }}"
        groups_action: add
        update_password: always
      ignore_errors: true
      when: account.secret_type == "password"

    - name: Refresh connection
      ansible.builtin.meta: reset_connection

    - name: Verify password
      ansible.windows.win_ping:
      vars:
        ansible_user: "{{ account.username }}"
        ansible_password: "{{ account.secret }}"
      when: account.secret_type == "password"
