ARG VERSION=dev

FROM registry.fortserver.com/fortserver/xpack:${VERSION} AS build-xpack
FROM fortserver/core:${VERSION}-ce

COPY --from=build-xpack /opt/xpack /opt/fortserver/apps/xpack

ARG TOOLS="                           \
        g++                           \
        curl                          \
        iputils-ping                  \
        netcat-openbsd                \
        nmap                          \
        telnet                        \
        vim                           \
        wget"

RUN set -ex \
    && apt-get update \
    && apt-get -y install --no-install-recommends ${TOOLS} \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/fortserver

ARG PIP_MIRROR=https://pypi.org/simple
COPY poetry.lock pyproject.toml ./
RUN set -ex \
    && . /opt/py3/bin/activate \
    && pip install poetry -i ${PIP_MIRROR} \
    && poetry config repositories.pypi ${PIP_MIRROR} \
    && poetry install --only xpack

