ARG VERSION
FROM registry.fortserver.com/fortserver/xpack:${VERSION} as build-xpack
FROM fortserver/core:${VERSION}
COPY --from=build-xpack /opt/xpack /opt/fortserver/apps/xpack

WORKDIR /opt/fortserver

RUN --mount=type=cache,target=/root/.cache/pip \
    set -ex \
    && pip install -r requirements/requirements_xpack.txt
