ARG VERSION
FROM registry.fortserver.com/fortserver/xpack:${VERSION} as build-xpack
FROM registry.fortserver.com/fortserver/core-ce:${VERSION}

COPY --from=build-xpack /opt/xpack /opt/fortserver/apps/xpack