- hosts: mysql
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python

  tasks:
    - name: Test MySQL connection
      community.mysql.mysql_info:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        filter: version
