- hosts: mysql
  gather_facts: no
  vars:
    ansible_python_interpreter: /opt/py3/bin/python
    jms_use_ssl: "{{ jms_asset.spec_info.use_ssl }}"

  tasks:
    - name: Verify account
      community.mysql.mysql_info:
        login_user: "{{ account.username }}"
        login_password: "{{ account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        check_hostname: "{{ omit if not jms_use_ssl else jms_asset.spec_info.allow_invalid_cert }}"
        ca_cert: "{{ omit if not jms_use_ssl else jms_asset.secret_info.ca_cert }}"
        client_cert: "{{ omit if not jms_use_ssl else jms_asset.secret_info.client_cert }}"
        client_key: "{{ omit if not jms_use_ssl else jms_asset.secret_info.client_key }}"
        filter: version
