- hosts: postgresql
  gather_facts: no
  vars:
    ansible_python_interpreter: /opt/py3/bin/python

  tasks:
    - name: Get info
      community.postgresql.postgresql_info:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        login_db: "{{ jms_asset.spec_info.db_name }}"
        filter: "roles"
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info: "{{ db_info.roles }}"

    - debug:
        var: info
