- hosts: mysql
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python

  tasks:
    - name: Get info
      community.mysql.mysql_info:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        check_hostname: "{{ jms_asset.spec_info.use_ssl and not jms_asset.spec_info.allow_invalid_cert }}"
        ca_cert: "{{ jms_asset.secret_info.ca_cert }}"
        client_cert: "{{ jms_asset.secret_info.client_cert }}"
        client_key: "{{ jms_asset.secret_info.client_key }}"
        filter: users
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info: "{{ db_info.users }}"

    - debug:
        var: info
