- hosts: testhost
  vars:
    ansible_user: root
    ansible_ssh_password: fortserver20202
    user1: web
    user1password: fortserver@12344

  tasks:
    - name: 监测特权用户密码
      ansible.builtin.ping:

    - name: 更改用户密码
      user:
        name: "{{ user1 }}"
        password: "{{ user1password|password_hash('sha512', 'K3mIlKK') }}"
        update_password: always

    - name: 校验密码是否更改成功
      vars:
        - ansible_user: '{{ user1 }}'
          ansible_ssh_password: '{{ user1password }}'
      ansible.builtin.ping:

